### ISSUE TITLE
Option to get dependency as a full git clone

### ISSUE THREAD

**Issue by tkarls** [buildinspace/peru#127] opened 2015-08-14 08:56 UTC
Just found Peru and think it looks very promising.

Although, I have one feature suggestion that I believe would make it even more useful.

If the directory that you get the dependency code in would in fact be a git clone. That way, if you as part of your project changes anything to the the imported module you can easily commit it and send it back upstream.

As it is now you must copy the changed files to another location where you have a clone already and it makes it a bit harder to work with.

It's fine if the clone checkout the sha1 commit as a detached head. Just keep the git info there to use if you need to :)

What do you think, is this desired? Is it possible to do?

**Comment by oconnor663** [comment] 2015-08-14 15:13
This is definitely our most common feature request, and it's the biggest doubt I have about whether we made the right design choices with peru. The short answer is that peru really isn't designed for that workflow, but the `override` feature exists to kinda sorta let you do that. Have you tried it?

Here's the long answer:

Peru is designed to run every time, inside whatever build/run script you have at the top of your project. The goal is that the human shouldn't need to *remember* any special build steps. This is important when you bounce around the history of your project, or when you pull new commits. Did your dependencies change? Do you need to sync again? By running peru every time, you never need to ask that question. Your build always does the Right Thing.

That goal means that peru needs to have substantial control over the files it puts on disk. It works a lot like `git checkout` in this way, and in fact, it uses git under the covers. When you run `peru sync` with new dependencies, peru will change existing files and clean up files that don't need to be there anymore. That's convenient (and more importantly, correct!) for dependencies that you never touch. But it means that peru needs to be cautious to avoid wiping out any changes you might've made. It'll raise an error if it sees that any files have changed since you last synced them.

And *that* goal in turn means that it's difficult to make peru play nicely with the workflow you described. Imagine peru cloned a git repo for you and put it directly in your project. As soon as you started editing files in that repo, peru would freak out and break your build. You'd need to switch to a workflow where you only called peru during setup or something, at which point you might as well just use git submodules. The `override` feature was designed to deal with this. It lets you change the *source* of one of your modules, to refer to your clone somewhere else on disk. The downsides are that you need to run `peru sync` in your main project every time you make a change in the module (though you should do that automatically anyway), and that the clones have to be side-by-side or something instead of nested.

So that's the Big Reason peru hasn't done this. There are side benefits, like the `pick` and `export` features, and being able to import the contents of two modules into the same directory, none of which would be possible with real clones. There are also performance concerns. Since peru expects to run every time, a cached sync should be very fast. We get that by storing all your imports as one big git tree, so that syncing in the best case boils down to a single `git status`. But git trees are not allowed to store a `.git` folder in themselves (for [security reasons](http://article.gmane.org/gmane.linux.kernel/1853266)), so this design is incompatible with laying out real git clones, at least without some serious hacks.

So yeah, that's probably more than you wanted to know :) I'm interested to hear more of your thoughts, especially about `override`.

**Comment by kydyl** [comment] 2015-08-17 06:58
Thanks for great reply!

Yea I totally agree with you that putting the peru sync in the buildfile is what you want. And then, as you say it would really fail the build if the dependency is modified.

I did not really notice the override command before. Let me try it out a little bit and see how it behaves and I'll get back to you.

**Comment by oconnor663** [comment] 2015-09-09 04:44
Closing for now. Let me know how you find `override`.

**Closed by oconnor663** 2015-09-09 04:44 UTC

**Comment by tkarls** [comment] 2015-09-10 08:10
Hi, yes I have had the opportunity to try out override a little bit in a real scenario and it kinda works.

Although I'm thinking if it would work better with hard links instead instead of copying in the folder from the location I specify. Because now if I edit a file when I'm using override peru sync gives an error (expected) and I then have to manually copy the change over to the "override origin" if you understand what I mean.

With a hard symlink I could edit the file in place in the peru controlled folder and it would keep the "override origin" in sync all the time.

I understand it could be considered "dangerous" but perhaps added as an option.?

**Comment by oconnor663** [comment] 2015-09-11 20:09
That's an interesting idea. It wouldn't work without modification, because what peru does right now is compared the files in your project to what they were the last time it synced (represented by a git tree hash stored at `.peru/lastimports`), rather than what they are in the source repo now. So even with hard links you'd run into the error. But we could hack around that in theory.

Can you tell me how you feel about either of the following options (I'm assuming bad, but I'm curious to learn more about your use case):

1. making your edits in the override clone rather than directly in your peru project (and then possibly having your test script or whatever invoke peru for you every time, to save you doing it by hand)
2. unifying your parent project and your dependency into a single repo
